sudo: false
dist: trusty
language: rust
cache: cargo
rust:
  - nightly
  - beta
  - stable
before_script:
  - rustup component add rustfmt
script:
  - cargo fmt --all -- --check
  - cargo build
  - cargo build --release
  - cargo test
  - cargo test --release
