[package]
name = "rtps-rs"
version = "0.1.2"
authors = ["Klapeyron <tomasz.bartos@protonmail.com>"]
description = "Real Time Publish Subscribe protocol"
repository = "https://github.com/Klapeyron/rtps-rs"
homepage = "https://github.com/Klapeyron/rtps-rs"
readme = "README.md"
keywords = ["protocol"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
bytes = "1.0.0"
tokio-util = { version = "0.5.1", features = ["codec"] }
bit-set = "0.5.2"
bit-vec = "0.6.3"
speedy = "0.7.1"
log = "0.4.11"
num-traits = "0.2"
num-derive = "0.3"
err-derive = "0.3"

[dev-dependencies]
pretty_assertions = "0.6.1"
