[package]
name = "rtps"
version = "0.1.0"
authors = ["Klapeyron <tomasz.bartos@protonmail.com>"]
edition = "2018"

[dependencies]
time = "0.1.39"
tokio-core = "0.1.17"
bit-set = "0.5.0"
bit-vec = "0.5.0"
speedy = "0.4.1"
speedy-derive = "0.3.1"
