[package]
name = "rtps-rs"
version = "0.1.1"
authors = ["Klapeyron <tomasz.bartos@protonmail.com>"]
description = "Real Time Publish Subscribe protocol"
repository = "https://github.com/Klapeyron/rtps-rs"
homepage = "https://github.com/Klapeyron/rtps-rs"
readme = "README.md"
keywords = ["protocol"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
bytes = "0.6.0"
tokio-util = { version = "0.5.0", features = ["codec"] }
bit-set = { git = "https://github.com/contain-rs/bit-set", rev ="c27082f" }
bit-vec = "0.6.2"
speedy = "0.7.1"
log = "0.4.8"
num-traits = "0.2"
num-derive = "0.3"
