[package]
name = "rtps"
version = "0.1.0"
authors = ["Klapeyron <tomasz.bartos@protonmail.com>"]
edition = "2018"

[dependencies]
time = "0.1.39"
serde = "1.0.70"
serde_derive = "1.0.27"
bit-set = "0.5.0"
bit-vec = "0.5.0"
cdr = { git = "https://github.com/hrektts/cdr-rs" }
