name: Update Cargo.lock

on:
  schedule:
  - cron: '0 0 1 * *'

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/cargo@v1
      name: Run cargo update
      with:
        command: update
    - uses: peter-evans/create-pull-request@v2
      name: Create Pull Request
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Automated Cargo.lock update
        title: Update Cargo.lock
        branch-suffix: random
